navbar setup with login functionality
werate-io/werate-explorer pull request #27
Opened 2024-09-17 09:25 UTC by Talhaaa99

2024-09-25 10:02 UTC, prabhanukash commented on src/components/Navbar.tsx
> +    const storedEmail = localStorage.getItem('email');
instead if email do check with token

2024-09-25 10:30 UTC, prabhanukash commented on src/services/werate-api.ts
> +};
move this auth service

2024-09-25 10:31 UTC, prabhanukash requested changes
please address comments

2024-09-27 11:37 UTC, Talhaaa99 commented on src/services/werate-api.ts
> +};
moved this

2024-09-27 11:37 UTC, Talhaaa99 commented on src/components/Navbar.tsx
> +    const storedEmail = localStorage.getItem('email');
using this to get initials, to avoid 2 api calls for faster response time

2024-09-27 17:09 UTC, verschaevesiebe commented
Please resolve conflicts @prabhanukash or @Talhaaa99

2024-09-30 12:34 UTC, merged

2024-09-30 12:35 UTC, verschaevesiebe commented
Looks good ! :)